#!/bin/bash

# Working directory
TOP="$(pwd)"

# Intro
cat<<INTRO

Backup tools for Android devices
Copyright (C) 2016 Simao Gomes Viana

Licensed under the Creative Commons \
Attribution-ShareAlike 4.0 International Public License \
(CC BY-SA 4.0)

Read the license on https://creativecommons.org/licenses/by-sa/4.0/legalcode \
or a short summary on https://creativecommons.org/licenses/by-sa/4.0/

INTRO

# Basic stuff
source $TOP/include/basic.sh

source $TOP/script/config/product.config

# Main entry point (must include function main)
source $MAIN_ENTRY_POINT

# Start
mainresult=0
main $@
mainresult=$?

# kthxbye
echo ""
exit $mainresult
