#!/bin/bash

reflectorName "Direct Tar Compression Backup"
reflectorId   "bktools_backup_c_directtar"

registerBackupModule directtar

function reflect() {
  logt "Hello."
  local devicepath="$1"
  local tarfile="$2"
  local resultcode=0
  runall adb_interface func adb_root
  return $resultcode
}
