#!/bin/bash

reflectorName "Direct Tar Compression Backup"
reflectorId   "bktools_backup_c_directtar"

registerBackupModule directtar

function reflect() {
  logt "Hello."
  local devicepath="$1"
  local tarfile="$2"
  local resultcode=0
  runall adb_interface func adb_root
  if [ $? -eq 0 ]; then
    sleep 0.2
    local pipe="/data/xd__backuptools/bk.pipe"
    adb_shell mkdir -p /data/xd__backuptools/
    adb_shell busybox mkfifo $pipe
    sleep 0.3
    echo "Backing up $devicepath to $tarfile..."
    adb exec-out 'busybox tar -cvap '"$devicepath"' 2>'"$pipe">$tarfile &
    adb shell cat $pipe
    sleep 0.2
    adb_shell rm -rf /data/xd__backuptools/
    echo -e "\n${CL_GREEN}Backup completed${CL_RESET}\n"
  fi
  return $resultcode
}
